### PR TITLE
Feather 0.3.0 release

### LINKED ISSUE #4: Commit access
Hello -- would it be possible for me to be granted commit rights on this repo? I can also submit a patch when we make the next Feather release if this is more convenient.

Thanks!

### PR DESCRIPTION
**Pull request by wesm**
Closes #4

### CODE REVIEW

**Comment by wesm** [comment]
Oops, we do not yet have Windows support here. I see that @dhirschfeld has a build on anaconda.org here

https://anaconda.org/dhirschfeld/feather-format

**Comment by ocefpaf** [comment]
@wesm the bot script that process the teams is tied to Travis-CI and that service is quite flaky lately. See how long the build itself is taking here. So it may be a few hours (days?!) util you are added to the feedstock team.

**Comment by wesm** [comment]
Can someone help with adding a Windows recipe + Appveyor CI? Last I checked this builds without problems with MSVC 14.0 on Python 3.5, not sure about Python 2.7

**Comment by ocefpaf** [comment]
> Can someone help with adding a Windows recipe + Appveyor CI? 

In theory you have to:
- remove the `skip: True  # [win]`
- rerender the recipe by calling `conda smithy rerender` at the root directory of the recipe

that will create the AppVeyor configuration for you and you can commit those changes. However, you still need to add the build script either as an entry in the `meta.yml`

``` yaml
script: python setup.py install --single-version-externally-managed --record record.txt  # [win]
```

or a `bld.bat` if you need to activate any flags or issue more build commands.

@msarahan and @patricksnape not sure what else may be needed here to build this on Windows.

**Comment by jakirkham** [comment]
Just FYI, we are having some problems uploading to Anaconda.org ATM. See issue ( https://github.com/conda-forge/status/issues/4 ) for details. We are working with Continuum on addressing this. If it is urgent to get this out, go for it. Just may need a bunch of CI restarts to get everything out. If not, it wouldn't hurt to hold off for a bit.

Should note that Travis CI is causing some issues ATM too. ( https://github.com/conda-forge/status/issues/6 ) So we will have to wait and see how that goes. It does appear to be improving.

**Comment by wesm** [comment]
Yikes. Hoping we have critical mass for community-owned/managed hosting for conda-forge someday (to distribute responsibility for uptime across multiple people and orgs)

**Comment by jakirkham** [comment]
Definitely there is great value in having multiple sources for workers and package hosts to mitigate the affect of problems from any one (i.e. Travis CI). We had a long talk today on this point with taking control of our own build workers. That being said, I don't know that it would help the upload problem per se.

This problem is caused because we have been doing something sort of silly partially due to limited options, which is costing us. See PR ( https://github.com/conda-forge/conda-smithy/pull/273 ) for a possible way to improve on this. Note the comments at the bottom about how we can try to go further. Continuum has actually been very helpful in working with us to try and solve this issue. We should be getting access to a new API that will help us be more efficient still.

**Comment by wesm** [comment]
> Continuum has actually been very helpful in working with us to try and solve this issue. We should be getting access to a new API that will help us be more efficient still.

No doubt, I just think it would be great to be able to do full stack testing / development with a completely open source stack (like testing the index API request performance at the 1000s of packages scale). At this stage of priorities leaving this work to the Continuum folks (as they have a vested interest in this system scaling). For example for PyPI we have https://github.com/pypa (but I've never tried setting up a PyPI myself of course, so there may be a lot more to it than what is on there).

**Comment by chris-b1** [comment]
@wesm - I think the approach in https://github.com/conda-forge/feather-format-feedstock/pull/2 is basically what is needed for Windows?  As noted there, might be issues with mixing MSVC runtimes, so maybe you only build for 3.5+?  cc: @jjhelmus

**Comment by wesm** [comment]
my understanding is there are some C++11 issues with 2.7 so I'm OK with this

**Comment by wesm** [comment]
cc @msarahan

**Comment by msarahan** [comment]
Yes, seems like mixing runtimes is the only real option you have right now.  Until there is a way to manage Python 2.7 environments that use non-standard compilers, this is dangerous, but perhaps workable.

**Comment by jjhelmus** [comment]
Can this be merged as-is and a Windows build be added later?  Would be nice to get feather 0.3.0 conda packages for OS X and Linux on conda-forge.

**Comment by msarahan** [comment]
Yep, fine with me.  Merging.

**Comment by SylvainCorlay** [comment]
@wesm you can force the use of msvc14 even with python 2.7. (Then it is important that you never de-allocate memory with one runtime that you allocated with the other runtime.)

The way to do this in you conda recipe would be
1. Add a runtime dependency to the msvc14 runtime only on windows
   `- vs2015_runtime  # [win]`
2. populate the bld.bat with

``` batch
if "%ARCH%" == "32" (set PLATFORM=x86) else (set PLATFORM=x64)
call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
set DISTUTILS_USE_SDK=1
set MSSdk=1
"%PYTHON%" setup.py install
if errorlevel 1 exit 1
```

**Comment by msarahan** [comment]
Just set the (still not adequately documented) msvc_compiler build entry in
meta.yaml.

```
build:
  msvc_compiler: 14.0
```

**Comment by SylvainCorlay** [comment]
> Just set the (still not adequately documented) msvc_compiler build entry in meta.yaml.

Is it equivalent to what I described?

**Comment by msarahan** [comment]
Yes. It applies the distutils flags you listed and runs the corresponding
vcvarsall.bat or equivalent.

**Comment by dhirschfeld** [comment]
In case it's of use I published an update py35 build to [anaconda.org](https://anaconda.org/dhirschfeld/feather-format)

```
λ py.test -v
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- C:\Python\python.exe
cachedir: .cache
rootdir: C:\Python\Lib\site-packages\feather\tests, inifile:
plugins: hypothesis-3.4.2, xdist-1.14
collected 19 items

test_reader.py::TestFeatherReader::test_boolean_no_nulls PASSED
test_reader.py::TestFeatherReader::test_boolean_nulls PASSED
test_reader.py::TestFeatherReader::test_boolean_object_nulls PASSED
test_reader.py::TestFeatherReader::test_category PASSED
test_reader.py::TestFeatherReader::test_empty_strings PASSED
test_reader.py::TestFeatherReader::test_file_not_exist PASSED
test_reader.py::TestFeatherReader::test_float_no_nulls PASSED
test_reader.py::TestFeatherReader::test_float_nulls PASSED
test_reader.py::TestFeatherReader::test_integer_no_nulls PASSED
test_reader.py::TestFeatherReader::test_integer_with_nulls PASSED
test_reader.py::TestFeatherReader::test_nan_as_null PASSED
test_reader.py::TestFeatherReader::test_non_string_columns PASSED
test_reader.py::TestFeatherReader::test_num_rows_attr PASSED
test_reader.py::TestFeatherReader::test_platform_numpy_integers PASSED
test_reader.py::TestFeatherReader::test_read_columns PASSED
test_reader.py::TestFeatherReader::test_sparse_dataframe PASSED
test_reader.py::TestFeatherReader::test_strings PASSED
test_reader.py::TestFeatherReader::test_timestamp PASSED
test_reader.py::TestFeatherReader::test_unicode_filename PASSED

========================== 19 passed in 2.44 seconds ==========================
```

**Pull request merged**
