### PR TITLE
TESTING DO NOT MERGE: Testing Windows build of GitHub master branch

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Building on Windows [fails](https://ci.appveyor.com/project/conda-forge/feather-format-feedstock/build/1.0.5) when Visual Studio 2008 (Python 2.7) or 2010 (Python 3.4) is used.  Visual Studio 2015 (Python 3.5) does work.

**Comment by jjhelmus** [comment]
Forcing the use of Visual Studio 2015 works on all versions of Python, although mixing msvc runtimes is a bit concerning as mentioned by @msarahan in #1.

**Comment by patricksnape** [comment]
I'm still really unsure of concrete examples of mixing CRT runtimes that are 'guaranteed' segmentation faults. However, linking like this definitely means that all bets are off with respect to stability on Python versions < 3.5.

**Comment by wesm** [comment]
Closed with #12 as Feather support is provided by pyarrow conda packages

**Pull request closed without merging**
