### PR TITLE
Adding windows build for py35.

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by msarahan** [comment]
This is a simple technical solution with enormous policy implications. This sets a precedent that demands extremely high technical knowledge and inspection. I am confident that Wes had this level of knowledge, but I am less confident that allowing this generally is a good idea. There needs to be some clear indicator for these packages that they are more risky than others.

**Comment by SylvainCorlay** [comment]
> This is a simple technical solution with enormous policy implications. 

Clearly :) The trick is don't delete in your c++ what the runtime of python allocated and vice-versa.

**Comment by msarahan** [comment]
The problem with that statement is that for the vast majority of packages here, the maintainers are just packagers, not developers of the package that they are packaging,  and they are not necessarily in a good place to fix or even understand this issue. You are immensely competent, but to expect that generally is overly optimistic. Unless there is an automated tool to check for such possible allocations and deallocations, this is unsafe at best.

**Comment by SylvainCorlay** [comment]
> The problem with that statement is that for the vast majority of packages here, the maintainers are just packagers, not developers of the package that they are packaging, and they are not necessarily in a good place to fix or even understand this issue. You are immensely competent, but to expect that generally is overly optimistic. Unless there is an automated tool to check for such possible allocations and deallocations, this is unsafe at best.

If the package author is using a framework for building extensions like pybind or boost.python, the risk is already somewhat mitigated.

**Comment by SylvainCorlay** [comment]
^ @wesm

**Comment by wesm** [comment]
So the issue here is that there may be interdependent C++ packages that are built with different VS runtimes? With Feather it seems OK since its use is self-contained. Are there other risks that I should be aware of?

**Comment by SylvainCorlay** [comment]
> So the issue here is that there may be interdependent C++ packages that are built with different VS runtimes? 

Yes, problems generally arise when dealing with memory allocation and IO.  But the interdependent packages include python itself which _is_ built with an old runtime.

However, a sane extension
- lets python free the memory that it allocated, it only decrements reference counts on python objects.
- uses the Python API to allocate a new Python object...

As of MSVC 2015 (and therefore Python 3.5), the runtime has been split into a compiler-version-independent component (the UCRT), and a windows-version dependent part which is shipped as part of windows 10 and as an update for earlier versions of windows. So the issues of C runtime versions with MSVC should be mitigated in the future. We should be able to build extensions with a newer compiler with less concerns.

**Comment by msarahan** [comment]
This was discussed at our last general meeting: https://github.com/conda-forge/conda-forge.github.io/pull/237/files/b746e9a819a729c29999a3e994d7ff89182d4825#diff-6c094e790914abc49860b71230c62919R46 - consensus was reached to not support this without better upstream support or some form of annotation that this package is potentially more volatile than others.  As an organization hosting feather-format packages, it would reflect poorly on us if our package caused support issues.

For upstream support, there are at least two avenues:
- Python upstream supports this build configuration as Python 2.8.  This is largely a dead discussion.
- Conda-build adds support for tracking python 2.7 ecosystems built with non-standard compilers.  This is a long-standing discussion, detailed at https://github.com/conda/conda-build/issues/1142

@SylvainCorlay @wesm since you were not present for that meeting, if you'd like to re-raise the issue, I invite you to add it to our agenda (https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG), and attend a future meeting (next one at Friday, 9/16, 9 AM Central time).  At the very least, I think that this PR requires a conda-forge enhancement proposal about how to handle this situation, in terms of what wrapper generation tools are "safe", what must be checked to ensure safety (in very specific terms - search patterns, analysis of code paths, good patterns, bad patterns, etc.) and the anticipated increase to reviewer competency and workload.  Our current proposal for that is at https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/1

CC @jjhelmus @ocefpaf @mingwandroid @mwcraig @pelson @jakirkham

**Comment by jakirkham** [comment]
Would using `clang` on Windows help us navigate some of these problems better? I don't really know much about it, but it seems to do a decent job of playing nice with VS runtimes and might separate C++ features into a separate knob from VS runtime.

**Comment by SylvainCorlay** [comment]
The worst-case scenario when using an extension built with another CRT than the one of python is a segfault on some IO or memory operation (if the author wasn't careful). Segfaults are already a possibility with pretty much any buggy C extension.

Besides, if this is forbidden, this prevents anyone from building extension for python 2.7 on windows that requires some C++11 features.

**Comment by wesm** [comment]
What do you think about posting Python 3.x MSVC builds only for now? cc @dhirschfeld

**Comment by patricksnape** [comment]
Personally I'm against this the option of building extensions with non-standard compilers as my understanding of the problem is that it is more subtle than purely allocating memory (`malloc`/`new`) with one CRT and deallocating (`free`/`delete`) it with another. At the very least I believe that @msarahan is correct in saying that we should put forward a CFEP for this as I would not be keen to support packages that were built with this non-standard packaging system and not explicitly labelled as such. As @msarahan mentioned - it is certainly possible to write code that will not run afoul of CRT differences - but it is nuanced and requires a package developer to understand the intricacies of the problem. 

> The worst-case scenario when using an extension built with another CRT than the one of python is a segfault on some IO or memory operation (if the author wasn't careful).

That's probably the worst outcome for us! Although you are correct in saying that segfaults are always possible, in general we want to avoid introducing them as part of the build environment rather than just buggy coding.

**Comment by jakirkham** [comment]
FYI I can't seem to follow your link to the meeting notes, @msarahan. It is leading me to a blank page. Could you maybe update it to point to notes in some in `master`? I'd just like myself and others to be able to understand what you are referencing. Thanks.

**Comment by wesm** [comment]
@patricksnape are you replying to me? Is there any reason to continue to block 3.5 builds on conda-forge?

**Comment by patricksnape** [comment]
@wesm No sorry, I update my first sentence a bit to reflect that I am not keen on the MSVC 2015 Python 2.7 builds. I would happy for you guys to get this in sans-Python 2.7.

**Comment by jakirkham** [comment]
Should we be dropping Python 3.4 too, @patricksnape @wesm? IIRC only Python 3.5 is targeted to play well with MSVC 2015.

**Comment by jakirkham** [comment]
Also I would invite people here to read (or re-read) issue ( https://github.com/conda-forge/conda-forge.github.io/issues/64 ).

**Comment by patricksnape** [comment]
Yes, in this case only Python 3.5+ would be shippable without having potential CRT issues.

**Comment by wesm** [comment]
OK great. @SylvainCorlay can you update the PR to only build for Python 3.5 and higher? I don't see any reason to block users on this any further while the separate discussion around mixing runtimes is ongoing

**Comment by SylvainCorlay** [comment]
Ok I will do this as soon as I get close to a keyboard.

**Comment by SylvainCorlay** [comment]
Done.

**Comment by wesm** [comment]
Sweet thanks. Merging

**Pull request merged**
